logging:
  level:
    com:
      wayly:
        back: INFO
spring:
  application:
    name: Waylyback
  jackson:
    default-property-inclusion: non_absent
server:
  port: 8080
springdoc:
  enable-native-support: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
